OUTPUT_DIR: "./logs/cuhk_coat"
INPUT:
  DATASET: "CUHK-SYSU"
  DATA_ROOT: "../../datasets/CUHK-SYSU"
  BATCH_SIZE_TRAIN: 4
SOLVER:
  MAX_EPOCHS: 14
  BASE_LR: 0.003
  LW_RCNN_SOFTMAX_2ND: 0.1
  LW_RCNN_SOFTMAX_3RD: 0.1
MODEL:
  LOSS:
    LUT_SIZE: 5532
    CQ_SIZE: 5000
DISP_PERIOD: 100
